# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': '',
                'git_url': 'https://github.com/doyu/boxrecipe',
                'lib_path': 'boxrecipe'},
  'syms': { 'boxrecipe.services': { 'boxrecipe.services.check_service': ('services.html#check_service', 'boxrecipe/services.py'),
                                    'boxrecipe.services.service_site': ('services.html#service_site', 'boxrecipe/services.py'),
                                    'boxrecipe.services.write_file_cmd': ('services.html#write_file_cmd', 'boxrecipe/services.py')}}}
