# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/',
                'doc_host': '',
                'git_url': 'https://github.com/doyu/boxrecipe',
                'lib_path': 'boxrecipe'},
  'syms': {}}
