"""box_recipe() folds every SERVICES entry plus WireGuard and the maintenance baseline into one cloud-init YAML — plus the live rebuild flow"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_box.ipynb.

# %% auto #0
__all__ = ['SERVICES', 'box_recipe']

# %% ../nbs/10_box.ipynb #f0768fa1
from hetznerinit.core import cloud_init_dict, cloud_init_yaml
from hetznerinit.wireguard import wg_server_cmds
from hetznerinit.caddy import caddyfile, caddy_cmds
from .services import check_service, service_site
from .discopipe import discopipe_service
from .reconcile import reconcile_service
from .habitrack import habitrack_service

def box_recipe(
    services:list,             # service dicts (see boxrecipe.services)
    peers:dict,                # {"e15": {"ip": "10.0.0.2", "pubkey": "..."}}
    ssh_key:str,               # SSH public key line for the login user
    hostname:str="doyu-box",   # cloud-init hostname
)->str:                        # full cloud-init YAML for the box
    """Compose the box's cloud-init: every service + WireGuard + a maintenance baseline."""
    if not isinstance(ssh_key, str) or not ssh_key.strip():
        raise ValueError("ssh_key must be a non-empty string")
    services = [check_service(s) for s in services]
    ports = [s["port"] for s in services if s.get("port") is not None]
    if len(ports) != len(set(ports)):
        raise ValueError(f"service ports must be unique, got {sorted(ports)}")
    sites = [b for b in (service_site(s) for s in services) if b]
    caddy = caddy_cmds(caddyfile(sites)) if sites else []  # no sites → skip Caddy entirely
    packages = ["wireguard", "byobu", "curl", "git",
                "debian-keyring", "debian-archive-keyring", "apt-transport-https"]
    for s in services:
        for p in s.get("packages", []):
            if p not in packages:
                packages.append(p)
    svc_cmds = [c for s in services for c in s.get("cmds", [])]
    return cloud_init_yaml(cloud_init_dict(
        hostname, "doyu", ssh_key,
        packages=packages,
        cmds=[*wg_server_cmds(peers), *caddy, *svc_cmds],
        udp_ports=51820,
    ))

# %% ../nbs/10_box.ipynb #efbceaab
SERVICES = [reconcile_service(), discopipe_service(), habitrack_service()]
