"""Cloud-init fragment for the discopipe bot: dedicated non-sudo user, venv install, claude CLI, agent CWD, hardened systemd unit"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_discopipe.ipynb.

# %% auto #0
__all__ = ['discopipe_service']

# %% ../nbs/01_discopipe.ipynb #36b1187d
from .services import check_service, write_file_cmd

_UNIT = """[Unit]
Description=discopipe - Discord passthrough to a headless coding agent CLI
After=network-online.target
Wants=network-online.target
ConditionPathExists=/etc/discopipe/env
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
User=discopipe
WorkingDirectory=/home/discopipe/agent
EnvironmentFile=/etc/discopipe/env
Environment=PATH=/home/discopipe/.local/bin:/usr/local/bin:/usr/bin:/bin
ExecStart=/opt/discopipe/bin/discopipe
Restart=on-failure
RestartSec=5
NoNewPrivileges=yes
ProtectSystem=strict
ReadWritePaths=/home/discopipe
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
"""

_CLAUDE_MD = """Replies are read on a phone via Discord. Keep every reply under 1800
characters. Be terse. For long output, write it to a file and reply with
the path and a 3-line summary.
"""

def discopipe_service(
)->dict:  # validated service dict for the discopipe bot (no domain, install+unit cmds)
    """Service dict for discopipe: outbound-only Discord bot, no Caddy block."""
    cmds = [
        "useradd --create-home --shell /usr/sbin/nologin discopipe",
        "python3 -m venv /opt/discopipe",
        "/opt/discopipe/bin/pip install git+https://github.com/doyu/discopipe.git",
        # runuser, not sudo: at early boot the clock can still be at the epoch, which
        # makes useradd's password age look expired and sudo's PAM refuses to run
        "runuser -u discopipe -- bash -c 'curl -fsSL https://claude.ai/install.sh | bash'",
        "install -d -m 700 -o root -g root /etc/discopipe",
        "install -d -o discopipe -g discopipe /home/discopipe/agent",
        write_file_cmd("/home/discopipe/agent/CLAUDE.md", _CLAUDE_MD,
                       owner="discopipe:discopipe"),
        write_file_cmd("/etc/systemd/system/discopipe.service", _UNIT),
        "systemctl daemon-reload",
        "systemctl enable discopipe",
    ]
    return check_service({"name": "discopipe", "domain": None, "port": None,
                          "public": False, "packages": ["python3-venv"], "cmds": cmds})
