"""Cloud-init fragment for the habitrack daily-habit tracker: dedicated system user, git clone + venv, writable data dir, hardened systemd unit"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_habitrack.ipynb.

# %% auto #0
__all__ = ['habitrack_service']

# %% ../nbs/03_habitrack.ipynb #17be2bc7
from .services import check_service, write_file_cmd

_UNIT = """[Unit]
Description=habitrack - single-user daily habit tracker (FastHTML over one CSV)
After=network-online.target
Wants=network-online.target
ConditionPathExists=/etc/habitrack/env
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
User=habitrack
WorkingDirectory=/opt/habitrack/app
EnvironmentFile=/etc/habitrack/env
Environment=PORT=5002
Environment=TZ=Europe/Helsinki
ExecStart=/opt/habitrack/venv/bin/python /opt/habitrack/app/app.py
Restart=on-failure
RestartSec=5
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/opt/habitrack/app/data
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
"""

def habitrack_service(
)->dict:  # validated service dict for the habitrack tracker (public site + install + unit cmds)
    """Service dict for habitrack: single-user habit tracker, session-auth gated."""
    cmds = [
        "useradd --system --no-create-home --shell /usr/sbin/nologin habitrack",
        "git clone https://github.com/doyu/habitrack.git /opt/habitrack/app",
        "python3 -m venv /opt/habitrack/venv",
        "/opt/habitrack/venv/bin/pip install -r /opt/habitrack/app/requirements.txt",
        # service user reads code+venv via group; X keeps the venv executable
        # whatever umask the surrounding cloud-init script runs under
        "chown -R root:habitrack /opt/habitrack",
        "chmod -R u=rwX,g=rX,o= /opt/habitrack",
        # the unit's ONLY writable path: the ledger is runtime state (DESIGN.md §3)
        "install -d -m 770 -o habitrack -g habitrack /opt/habitrack/app/data",
        "install -d -m 700 -o root -g root /etc/habitrack",
        write_file_cmd("/etc/systemd/system/habitrack.service", _UNIT),
        "systemctl daemon-reload",
        "systemctl enable habitrack",
    ]
    # public=True: the phone has no always-on VPN — the app's session auth is the gate
    return check_service({"name": "habitrack", "domain": "habitrack.ninjalabo.ai",
                          "port": 5002, "public": True,
                          "packages": ["python3-venv"], "cmds": cmds})
