"""Cloud-init fragment for the reconcile-web viewer: dedicated system user, venv install, archive dir, hardened systemd unit"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_reconcile.ipynb.

# %% auto #0
__all__ = ['reconcile_service']

# %% ../nbs/02_reconcile.ipynb #f6a7b8c9
from .services import check_service, write_file_cmd

_UNIT = """[Unit]
Description=reconcile - read-only web viewer over the reconcile-archive bookkeeping data
After=network-online.target
Wants=network-online.target
ConditionPathExists=/etc/reconcile/env
ConditionPathIsDirectory=/srv/reconcile-archive
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
User=reconcile
EnvironmentFile=/etc/reconcile/env
ExecStart=/opt/reconcile/bin/uvicorn --factory reconcile_web.app:create_app --host 127.0.0.1 --port 5001
Restart=on-failure
RestartSec=5
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
"""

def reconcile_service(
)->dict:  # validated service dict for the reconcile-web viewer (public site + install + unit cmds)
    """Service dict for reconcile-web: read-only bookkeeping viewer, app-password gated."""
    cmds = [
        "useradd --system --no-create-home --shell /usr/sbin/nologin reconcile",
        # doyu joins group reconcile: without membership, the kernel silently
        # clears the setgid bit on rsync's --chmod=D2750 dirs, so pushed files
        # fall back to group doyu and the service user cannot read the archive
        "usermod -aG reconcile doyu",
        "python3 -m venv /opt/reconcile",
        "/opt/reconcile/bin/pip install git+https://github.com/doyu/reconcile-web.git",
        # group-read for the service user, nothing for others; X keeps the venv
        # executable whatever umask the surrounding cloud-init script runs under
        "chown -R root:reconcile /opt/reconcile",
        "chmod -R u=rwX,g=rX,o= /opt/reconcile",
        # rsync target: doyu pushes from the laptop, setgid keeps group reconcile
        "install -d -m 2750 -o doyu -g reconcile /srv/reconcile-archive",
        "install -d -m 700 -o root -g root /etc/reconcile",
        write_file_cmd("/etc/systemd/system/reconcile.service", _UNIT),
        "systemctl daemon-reload",
        "systemctl enable reconcile",
    ]
    # public=True: the accountant has no VPN — APP_PASSWORD is the gate
    return check_service({"name": "reconcile", "domain": "reconcile.ninjalabo.ai",
                          "port": 5001, "public": True,
                          "packages": ["python3-venv"], "cmds": cmds})
