"""The service model: a plain dict per service, validated, rendered to Caddy blocks and guarded file-write cmds"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_services.ipynb.

# %% auto #0
__all__ = ['check_service', 'service_site', 'write_file_cmd']

# %% ../nbs/00_services.ipynb #bace4f18
def check_service(
    svc:dict,  # service dict: name, domain, port, public, packages, cmds
)->dict:       # the same dict, validated
    """Validate a service dict against the service model; return it unchanged."""
    if not isinstance(svc, dict):
        raise ValueError(f"service must be a dict, got {type(svc).__name__}")
    name = svc.get("name")
    if not isinstance(name, str) or not name.strip():
        raise ValueError(f"service name must be a non-empty string, got {name!r}")
    domain, port = svc.get("domain"), svc.get("port")
    public = svc.get("public", False)
    if not isinstance(public, bool):
        raise ValueError(f"{name}: public must be a bool, got {public!r}")
    if domain is None:
        if public:
            raise ValueError(f"{name}: domain=None with public=True (nothing to publish)")
    else:
        if isinstance(port, bool) or not isinstance(port, int) or not 1 <= port <= 65535:
            raise ValueError(f"{name}: a service with a domain needs a port in 1-65535, got {port!r}")
    for key in ("packages", "cmds"):
        val = svc.get(key, [])
        if not isinstance(val, list) or not all(isinstance(x, str) for x in val):
            raise ValueError(f"{name}: {key} must be a list of str, got {val!r}")
    return svc

# %% ../nbs/00_services.ipynb #49a305b2
from hetznerinit.caddy import caddy_site

def service_site(
    svc:dict,     # a service dict (validated here via check_service)
)->str|None:      # Caddyfile site block, or None when the service has no domain
    """Render a service's Caddy site block; VPN-gated unless public."""
    svc = check_service(svc)
    if svc.get("domain") is None:
        return None
    if svc.get("public", False):
        return caddy_site(svc["domain"], svc["port"], vpn_subnet=None)
    return caddy_site(svc["domain"], svc["port"])

# %% ../nbs/00_services.ipynb #deb939aa
import re

def write_file_cmd(
    path:str,                 # absolute path to write on the box
    content:str,              # file content (must not contain the heredoc delimiter)
    owner:str="root:root",    # chown owner:group
    mode:str="0644",          # chmod mode
)->str:                       # one cloud-init runcmd line (heredoc write + chown + chmod)
    """Return a guarded-heredoc runcmd line that writes content to path, then sets owner and mode."""
    # every value below lands in a root shell: whitelist instead of quoting
    # (same rule as hetznerinit's wg_server_cmds)
    if not isinstance(path, str) or not re.fullmatch(r"/[A-Za-z0-9._/-]+", path):
        raise ValueError(f"path must be absolute using [A-Za-z0-9._/-], got {path!r}")
    if not isinstance(owner, str) or not re.fullmatch(r"[a-z_][a-z0-9_-]*:[a-z_][a-z0-9_-]*", owner):
        raise ValueError(f"owner must be user:group, got {owner!r}")
    if not isinstance(mode, str) or not re.fullmatch(r"0?[0-7]{3}", mode):
        raise ValueError(f"mode must be 3 octal digits (optional 0 prefix), got {mode!r}")
    if "WF_EOF" in content:
        raise ValueError("content must not contain the heredoc delimiter 'WF_EOF'")
    return (f"cat > {path} <<'WF_EOF'\n{content.rstrip(chr(10))}\nWF_EOF\n"
            f"chown {owner} {path}\nchmod {mode} {path}")
